### ISSUE TITLE
Fix track duration for track url paths using ReadStream

### ISSUE THREAD

**Issue by ridhwaans** [kosmetism/react-soundplayer#96]
In the `SoundCloud.prototype.play = function (options) {` method of `react-soundplayer`, I have 
```
let streamUrl = this._playlist.tracks.items[this._playlistIndex].url_path || 
                      this._playlist.tracks.items[this._playlistIndex].preview_url
```
which plays a track from a url path ending in `.mp3`. The track plays however the duration and progress bar do not work as expected.  it always shows `00:00/00:00` when the track is playing
 
for example, a preview_url has a url 
`https://p.scdn.co/mp3-preview/136510b30afe553006aa8f5ef34fec48139f4fe3?cid=774b29d4f13844c495f206cafdad9c86` and duration is 0:00/2:26
and a url_path can be any filesystem path `https://localhost...` or ending in `.mp3` -> `/mnt/c...mp3`

code which returns track using `ReadStream.pipe`:
```
app.get('some endpoint containing track id', function(req, res) {
  var track_fs_path = // get filesystem full path of track from track id

  const path = track_fs_path
  const stat = fs.statSync(path)
  const head = {
      'Content-Type': 'audio/mpeg',
      'Content-Length': stat.size
  }
  res.writeHead(200, head);
  fs.createReadStream(path).pipe(res);
});
```

**Comment by voronianski** [comment]
@ridhwaans the code you're mentioning here

> In the SoundCloud.prototype.play = function (options) { method of react-soundplayer, I have
`let streamUrl = this._playlist.tracks.items[this._playlistIndex].url_path || this._playlist.tracks.items[this._playlistIndex].preview_url`

is from https://github.com/voronianski/soundcloud-audio.js

Also component, that [displays](https://github.com/kosmetism/react-soundplayer/blob/master/src/components/Timer.js#L34) the duration, [is receiving `currentTime` value](https://github.com/kosmetism/react-soundplayer/blob/master/src/addons/withSoundCloudAudio.js#L150-L154) from the actual [audio element instance](https://github.com/voronianski/soundcloud-audio.js/blob/master/index.js#L61)

I need to check whether the problem is in component or in audio lib. If you can provide some kind of reproductiin environment that would be helpful. Thanks for reporting!

**Comment by ridhwaans** [comment]
What do you mean by reproduction environment? the steps I can reproduce are:  
1. create a small node express client running locally on port 5000 for example
2. use app.get function to expose a url endpoint that 
    2a. opens a music file from filesystem address
    2b. returns readstream of file same as the code above
    2c. example url: localhost:5000/api/music_file1.mp3
3. Pass url path as react state to `this._playlist.tracks.items[this._playlistIndex].url_path` while node app is running  
Works on both Mac and windows

**Comment by ridhwaans** [comment]
has there been any fixes/investigation?
